name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - name: Install rescript-throttle deps
        run: yarn install
        working-directory: ./rescript-throttle

      - name: Install rescript-throttle-react deps
        run: yarn install
        working-directory: ./rescript-throttle-react

      - name: Build rescript-throttle
        run: yarn run build
        working-directory: ./rescript-throttle

      - name: Build rescript-throttle-react
        run: yarn run build
        working-directory: ./rescript-throttle-react

      - name: Test rescript-throttle
        run: yarn run test
        working-directory: ./rescript-throttle
